
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "periodictable", targetNamespace = "http://www.webserviceX.NET", wsdlLocation = "file:/D:/training/practice/InterfaceGenerator/periodictable/PeriodicTable.wsdl")
public class Periodictable
    extends Service
{

    private final static URL PERIODICTABLE_WSDL_LOCATION;
    private final static WebServiceException PERIODICTABLE_EXCEPTION;
    private final static QName PERIODICTABLE_QNAME = new QName("http://www.webserviceX.NET", "periodictable");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/training/practice/InterfaceGenerator/periodictable/PeriodicTable.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERIODICTABLE_WSDL_LOCATION = url;
        PERIODICTABLE_EXCEPTION = e;
    }

    public Periodictable() {
        super(__getWsdlLocation(), PERIODICTABLE_QNAME);
    }

    public Periodictable(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERIODICTABLE_QNAME, features);
    }

    public Periodictable(URL wsdlLocation) {
        super(wsdlLocation, PERIODICTABLE_QNAME);
    }

    public Periodictable(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERIODICTABLE_QNAME, features);
    }

    public Periodictable(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Periodictable(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PeriodictableSoap
     */
    @WebEndpoint(name = "periodictableSoap")
    public PeriodictableSoap getPeriodictableSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET", "periodictableSoap"), PeriodictableSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeriodictableSoap
     */
    @WebEndpoint(name = "periodictableSoap")
    public PeriodictableSoap getPeriodictableSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET", "periodictableSoap"), PeriodictableSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERIODICTABLE_EXCEPTION!= null) {
            throw PERIODICTABLE_EXCEPTION;
        }
        return PERIODICTABLE_WSDL_LOCATION;
    }

}
