
package com.bcc.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentListServiceService", targetNamespace = "http://service.bcc.com/", wsdlLocation = "file:/D:/training/practice/InterfaceGenerator/student/Student.wsdl")
public class StudentListServiceService
    extends Service
{

    private final static URL STUDENTLISTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTLISTSERVICESERVICE_EXCEPTION;
    private final static QName STUDENTLISTSERVICESERVICE_QNAME = new QName("http://service.bcc.com/", "StudentListServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/training/practice/InterfaceGenerator/student/Student.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTLISTSERVICESERVICE_WSDL_LOCATION = url;
        STUDENTLISTSERVICESERVICE_EXCEPTION = e;
    }

    public StudentListServiceService() {
        super(__getWsdlLocation(), STUDENTLISTSERVICESERVICE_QNAME);
    }

    public StudentListServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTLISTSERVICESERVICE_QNAME, features);
    }

    public StudentListServiceService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTLISTSERVICESERVICE_QNAME);
    }

    public StudentListServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTLISTSERVICESERVICE_QNAME, features);
    }

    public StudentListServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentListServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentListService
     */
    @WebEndpoint(name = "StudentListServicePort")
    public StudentListService getStudentListServicePort() {
        return super.getPort(new QName("http://service.bcc.com/", "StudentListServicePort"), StudentListService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentListService
     */
    @WebEndpoint(name = "StudentListServicePort")
    public StudentListService getStudentListServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bcc.com/", "StudentListServicePort"), StudentListService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTLISTSERVICESERVICE_EXCEPTION!= null) {
            throw STUDENTLISTSERVICESERVICE_EXCEPTION;
        }
        return STUDENTLISTSERVICESERVICE_WSDL_LOCATION;
    }

}
