
package com.bcc.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentListService", targetNamespace = "http://service.bcc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentListService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.bcc.service.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://service.bcc.com/", className = "com.bcc.service.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://service.bcc.com/", className = "com.bcc.service.GetStudentsResponse")
    @Action(input = "http://service.bcc.com/StudentListService/getStudentsRequest", output = "http://service.bcc.com/StudentListService/getStudentsResponse")
    public List<Student> getStudents(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

}
